### ISSUE TITLE
Option to add a device only via the cloud

### ISSUE THREAD

**Issue by stankiewiczmichal** [ZeliardM/homebridge-kasa-python#1]
Hi. It would be very useful to have the option to add devices that are on different Wi-Fi networks, while connected to one Kasa account. Currently, I have such a situation that I am using a TP-Link HS-100, which is on a separate network from the device on which Homebridge is. Would it be possible to add such a feature? I would really appreciate it, especially because I have not found any other extension for this device that works in any way through the cloud.

**Comment by ZeliardM** [comment]
Hey, I can look at the functionality of the manual device list and using it to add devices based on IP Address if the device can be found by the Homebridge Server.

I'll work on the functionality and provide a beta that I can get you to test for me if that works?

**Comment by stankiewiczmichal** [comment]
I will be happy to test the beta, but the option to find by IP address will not work here either, because the devices are in completely separate networks. Unfortunately, searching by cloud or using some other identifier (by name or serial?) is required here :/

**Comment by ZeliardM** [comment]
Unfortunately, the Python-Kasa Library which I'm using only connects via local network broadcast discovery. This plug-in does not connect the TP-Link Kasa Cloud at all.

You can read more about the library itself here:
https://github.com/python-kasa/python-kasa

Have you tried the homebridge-tplink-smarthome platform here?
https://github.com/plasticrake/homebridge-tplink-smarthome

**Comment by stankiewiczmichal** [comment]
Hi, yes I tried, while it does not work in the way I need

**Comment by ZeliardM** [comment]
I'm sorry to hear that. Unfortunately, my plug-in will require direct access to the devices to discover, query, and interact with them because of the python-kasa library that is used.

Sorry I couldn't be more help.
