### ISSUE TITLE
Failure to discover devices

### ISSUE THREAD

**Issue by juan2three** [ZeliardM/homebridge-kasa-python#11]
**Describe The Bug:**
After connecting 2 HS103 plugs and installing the plugin, the plugin fails to find them in the network
**To Reproduce:**
Connect wall plugs to the network, run the plug in or add them manually to the config then run the plugin

**Expected behavior:**
Devices are found by the plugin

**Logs:**
```[12/3/2024, 10:55:13 PM] [KasaPython] Initializing KasaPython platform...
[12/3/2024, 10:55:15 PM] [KasaPython] Source file not found.
[12/3/2024, 10:55:26 PM] [KasaPython] Discovering devices...
[12/3/2024, 10:55:26 PM] [KasaPython] An error occurred during device discovery: connect ECONNREFUSED 127.0.0.1:37809
[12/3/2024, 10:55:26 PM] [KasaPython] No devices found.
[12/3/2024, 11:07:05 PM] [KasaPython] [Python Check] WARNING: The directory '/home/homebridge/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
```
**Plugin Config:**

```{
    "name": "KasaPython",
    "enableCredentials": false,
    "pollingInterval": 3,
    "additionalBroadcasts": [
        "192.168.159.255"
    ],
    "manualDevices": [
        {
            "host": "192.168.159.111",
            "alias": "tree"
        }
    ],
    "platform": "KasaPython"
}
```

**Environment:**

* **Plugin Version**: v2.6.8
* **Homebridge Version**:  1.8.5
* **Node.js Version**: v22.11.0
* **NPM Version**: 10.9.0
* **Operating System**: Raspbian/hb-service 
* **Router**: Firewalla

**Comment by ZeliardM** [comment]
Looks like there may have been a problem installing the plugin? It says it couldn't find the source files. Can you enable debug mode on Homebridge, uninstall the plugin, re-install it, and grab logs from the main Homebridge Logs not just the plugin logs? Something doesn't seem to get setup right. Sorry, haven't seen this one yet, so it will be a lot of try this and that to figure it out. Thanks!

**Comment by juan2three** [comment]
[homebridge.log.txt](https://github.com/user-attachments/files/18011550/homebridge.log.txt)

**Comment by ZeliardM** [comment]
@juan2three Ok, that log looks better this time, it looks like it installed the plugin correctly now, started loading the environment. The api server isn't responding. I modified the checking process for a response from the server in v2.6.9. Update to v2.6.9 and give it a shot and let me know.

**Comment by juan2three** [comment]
@ZeliardM Looks like we're back at the source error 
[homebridge.log.txt](https://github.com/user-attachments/files/18013964/homebridge.log.txt)

**Comment by ZeliardM** [comment]
Ok, I think I found the problem. Give me a bit to look into it.

**Comment by ZeliardM** [comment]
@juan2three try v2.6.10 and let me know.

**Comment by ZeliardM** [comment]
@juan2three also, what version of python are you running?

**Comment by juan2three** [comment]
@ZeliardM 3.11.2
[still getting a server error unfortunately](https://github.com/user-attachments/files/18017510/homebridge.log.txt)

**Comment by ZeliardM** [comment]
@juan2three I'm seeing a bunch of restarts and config changes, when you update the plugin are you manually making changes in other places and restarting homebridge? looking at the logs it's like its being told to restart before it finishes setting up the python environment which can cause problems. Please downgrade to v2.6.9, then restart the child bridge, upgrade to v2.6.10 and restart the child bridge, now watch the child bridge log. don't make any changes to homebridge or other plugins or restart anything else manually. can you then post the child bridge log?

**Comment by ZeliardM** [comment]
@juan2three actually, just upgrade to v2.6.11 and restart just the child bridge. watch the child bridge logs and when it finishes, post them here. Don't restart or change anything else.

**Comment by juan2three** [comment]
@ZeliardM Sorry for the wait, should be the last few lines of the file
[homebridge.log.txt](https://github.com/user-attachments/files/18028767/homebridge.log.txt)

**Comment by ZeliardM** [comment]
@juan2three not a problem. Can you enable debug logging from the Homebridge UI Settings and restart the plugin and post again, please and thank you. It seems to be running into problems during the python check with connecting to something.

**Comment by juan2three** [comment]
@ZeliardM The debug flag wasn't going through unless I restarted HB
[homebridge.log.txt](https://github.com/user-attachments/files/18029158/homebridge.log.txt)

**Comment by ZeliardM** [comment]
@juan2three try v2.6.12, restart the child bridge, and post the child bridge logs. Keep debug on.

**Comment by juan2three** [comment]
@ZeliardM 
[homebridge-kasa-python.log.txt](https://github.com/user-attachments/files/18029523/homebridge-kasa-python.log.txt)

**Comment by ZeliardM** [comment]
@juan2three Ok, so it seems like it's having a problem access the files to run the python library. Update to v2.6.13 and let's try again. I was using a location that worked for I believe imaged installation not installations that were installed on the base operating system like yours. I have updated it now to work with both.

**Comment by juan2three** [comment]
@ZeliardM you're amazing. So we got 1 of them to work, the other one throws an error because I had the default "plug" name but the plugin reads it as "null". I changed it on the app to "reindeer" but the plugin isn't parsing it yet
[homebridge-kasa-python.log (1).txt](https://github.com/user-attachments/files/18030548/homebridge-kasa-python.log.1.txt)

**Comment by ZeliardM** [comment]
@juan2three You'll have to restart the plug-in to get it to discover it. I don't have periodic discovery set up yet.

**Comment by juan2three** [comment]
I'll mess around with this because the "plug" name is either cached on my local instance or the kasa app. We can close this ticket. Thank you for staying on top of it

**Comment by ZeliardM** [comment]
Ok, I'm also going to implement a default naming convention for alias if it's empty for this case as well.

**Comment by juan2three** [comment]
Sweet, thank you. I even reset the plug but the RPI seems to be caching the name. Here is the error fyi
```
[12/5/2024, 7:53:24 PM] [KasaPython] Adding: [null] SMART.TAPOSWITCH [802413ABF2AF844D77DBAD416342DB9D2227E6AD]
[12/5/2024, 7:53:24 PM] [KasaPython] [null] Creating new Accessory [802413ABF2AF844D77DBAD416342DB9D2227E6AD] [13891fba-8882-434b-8bf5-b349b4cfd6f6] category: SWITCH
[12/5/2024, 7:53:24 PM] [KasaPython] An error occurred during startup: AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at HomeKitDeviceSwitch.initializeAccessory (file:///usr/local/lib/node_modules/homebridge-kasa-python/src/devices/index.ts:46:19)
    at new HomekitDevice (file:///usr/local/lib/node_modules/homebridge-kasa-python/src/devices/index.ts:35:37)
    at new HomeKitDeviceSwitch (file:///usr/local/lib/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:18:5)
    at create (file:///usr/local/lib/node_modules/homebridge-kasa-python/src/devices/create.ts:30:12)
    at KasaPythonPlatform.createHomekitDevice (file:///usr/local/lib/node_modules/homebridge-kasa-python/src/platform.ts:180:12)
    at KasaPythonPlatform.foundDevice (file:///usr/local/lib/node_modules/homebridge-kasa-python/src/platform.ts:379:48)
    at file:///usr/local/lib/node_modules/homebridge-kasa-python/src/platform.ts:234:16
    at Array.forEach (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
```

**Comment by ZeliardM** [comment]
@juan2three Try the latest v2.7.0-beta.2, let me know.

**Comment by juan2three** [comment]
@ZeliardM 
[homebridge-kasa-python.log (2).txt](https://github.com/user-attachments/files/18043041/homebridge-kasa-python.log.2.txt)
Seems to have flush the cache because it now reads as "reindeer" but it added both switches as duplicates with variable names

Edit: I lied, the "duplicates" are some Tapo wall switches I have

**Comment by ZeliardM** [comment]
can you unplug them and restart your router and plug them back in? the network may have duplicate ip's stuck in the dhcp pool.

**Comment by ZeliardM** [comment]
@juan2three give v2.7.0-beta.3 a try and let me know.

**Comment by ZeliardM** [comment]
@juan2three give v2.7.0-beta.4 a shot and let me know how it's working.

**Comment by juan2three** [comment]
@ZeliardM Everything is working fine on beta 5!

**Comment by ZeliardM** [comment]
@juan2three Ok, excellent. I have some other changes to push out with a beta 6 shortly, I'll ask for you to check that one as well and if we're good, I think we can close this one out.

**Comment by ZeliardM** [comment]
@juan2three give v2.7.0-beta.6 a shot and let me know.

**Comment by ZeliardM** [comment]
@juan2three I added the feature for periodic discovery interval in seconds to be triggered and added an offlineInterval to determine how long in days devices need to be offline before they are removed.

**Comment by perezjuanj** [comment]
@ZeliardM sweet, thank you for all your help!!

**Comment by ZeliardM** [comment]
@juan2three @perezjuanj If things look good on your end, let's close this issue out and if something else arises, open another. Thanks!
