### ISSUE TITLE
v2.7.0-beta.5 - Initial state is never set

### ISSUE THREAD

**Issue by MichaelCWarren** [ZeliardM/homebridge-kasa-python#15]
After a fresh install, the initial state of an accessory is never set. 

When the device is changed for the first time, updates begin as normal.  I only have plugs and lights to test with, but they both seem be be affected.

```
if (service && this.previousKasaDevice) {
```

I'm thinking it has something to do with that line...  is a previousKasaDevice ever set initially?

**Comment by ZeliardM** [comment]
@MichaelCWarren Yea, when I changed how the values were updated, it never pulls from the device initially. I've made some changes to fix that with the next beta. Still working on the addition of the offline status tracking and removal.

**Comment by ZeliardM** [comment]
@MichaelCWarren give v2.7.0-beta.6 a shot and let me know.

**Comment by ZeliardM** [comment]
@MichaelCWarren I added the feature for periodic discovery interval in seconds to be triggered and added an offlineInterval to determine how long in days devices need to be offline before they are removed.

**Comment by MichaelCWarren** [comment]
Started up just fine. I'll keep an eye on it!

**Comment by MichaelCWarren** [comment]
@ZeliardM I did notice that when we can't connect to a device in kasaApi.py get_sys_info. The connect call is outside the try catch and we don't get a valid error, just a connection reset.  At least I think that is what was happening. I might try and recreate what I was seeing last night and make a PR.

**Comment by ZeliardM** [comment]
@MichaelCWarren It should be caught on Line 253 in the exception from the main route that calls the get_sys_info. Let me know what you find.

**Comment by MichaelCWarren** [comment]
Oh duh.  Not sure what was causing the connection resets then...

**Comment by ZeliardM** [comment]
@MichaelCWarren What version were you using? Do you remember what happened exactly? What error?

**Comment by MichaelCWarren** [comment]
@ZeliardM I believe it was .5.  Nothing changed with my setup AFAIK.  Unfortunately I don't have a log from that time, but it was checking the state of one of my light switches and getting an ECONNRESET from the python server.  Which led me (incorrectly) to that line of code.

**Comment by ZeliardM** [comment]
@MichaelCWarren Ok, I'm going to push out a beta 7 with some additional logging enabled and a new option to disable logging in the settings if desired. Give it a shot when it's available.
