### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by kemayo** [ZeliardM/homebridge-kasa-python#5]
**Is your feature request related to a problem? Please describe:**
This should support Python 3.13.

**Describe the solution you'd like:**
Add `3.13` to the list of supported python versions.

**Additional context:**
`python-kasa` says it supports python 3.13, so this shouldn't cause any issues.

**Comment by ZeliardM** [comment]
@kemayo What is the rest of your Homebridge setup like? What OS are you installed on? Do you have python 3.13 already installed? The plug-in should support it already. Do you get any errors when trying to install the plug-in with python 3.13?

**Comment by kemayo** [comment]
It's a standard Mac with python installed via homebrew, so everything is kept fairly bleeding-edge.

My experience with installing the plugin was that it started putting `[KasaPython] [Python Check] Python 3.13.0 is installed. However, only Python 3.9, 3.10, 3.11, 3.12 is supported.` in the log. (See: [SUPPORTED_PYTHON_VERSIONS](https://github.com/ZeliardM/homebridge-kasa-python/blob/404a3d8885e296ec98dc916f9ecd64442f824582/src/python/pythonChecker.ts#L12).) It's possible that this was just cosmetic and it'd keep on working fine, but stopping it from complaining seems like a good idea.

**Comment by ZeliardM** [comment]
Ah, yes, found my mistake there. I have corrected it, and it will be pushed out during the update to v2.5.8. The library will be dropping support for any version of Python lower than 3.11 soon, so there will be an update to cover that as well.

**Comment by kemayo** [comment]
Thanks!
